name: expense_tracker
description: Xtracker - Pencatat Pengeluaran Harian
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.3.3
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_slidable: ^3.1.0
  animate_do: ^3.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/